services:
  app:
    volumes:
      - ./.env:/app/.env

    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "4321"
    restart: unless-stopped

  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    expose:
      - "8080"
      - "5001"
    volumes:
      - ./data/libsql:/var/lib/sqld
